a=int(input("Enter a integer"))
b=float(input("Enter a floating point number"))
c=input("Enter a character")
d=bool(input("Enter a boolean value"))  
print(a,'is',type(a))
print(b,'is',type(b))
print(c,'is',type(c))
print(d,'is',type(d))
print("Double datatype doesnot exist")
